version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.6
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms750m -Xmx750m
    ports:
      - 9200:9200
      - 9300:9300

  jupyter:
    image: jupyter:v1
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - ./notebooks:/home/jovyan/work
    ports:
      - 8888:8888
    command: "start-notebook.sh --NotebookApp.token="
